language: java
jdk:
 - oraclejdk8
 before_script:
 - mkdir lib/
 - wget -P "lib/" https://github.com/kleinermatias/BITSoftware/blob/master/javacsv.jar
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    sources:
    - lib
    packages:
    - javacsv
